# Created by thopper91(2017)
#
# Variables will need to be changed based on your environment
---
- hosts: localhost
  vars:
    iLo_IP: '10.41.0.14'
    iLo_username: 'admin'
    iLo_password: 'Asi.2019'
    iso_image: 'http://10.41.0.10/esxi.iso'

  tasks:
    - name: Boot the system with an ISO
      hpilo_boot:
        force: true
        host: "{{ iLo_IP }}"
        login: "{{ iLo_username }}"
        password: "{{ iLo_password }}"
        media: cdrom
        image: "{{ iso_image }}"
      delegate_to: localhost

    - name: Power off the server
      hpilo_boot:
        host: "{{ iLo_IP }}"
        login: "{{ iLo_username }}"
        password: "{{ iLo_password }}"
        state: poweroff
      delegate_to: localhost